### PR TITLE
UI-II

### PR DESCRIPTION
**Pull request by znjs**
Added

:white_check_mark:  Profile page
:white_check_mark: Suggestions pane
:white_check_mark: Routing

### CODE REVIEW

**Review by muskaanshah — APPROVED** [review]
Like the design of your side panel and user profile card, good to merge

**Review by shraddha-amber — APPROVED** [review]
Code looks good
Profile page ui looks good too

Might change the size of the follow button in the suggestion panel

**Review by Nikhil-Nirmal — APPROVED** [review]
Good Looks to merge

**Comment by Nikhil-Nirmal** [comment]
Just a suggestion: Align the create new post button with home and other components will look good.

**Pull request merged**
